C***********************************************************************************
C
C   PROGRAM TO PROCESS GEANT OUTPUT
C   Through the arrays, profiles of the phantom with photons and electrons can be
C   made Each position of one array represents a silicon microstrip.
C   INPUT: phot.dat: Contains information of the photons which traversed the phantom
C           and are in the region of the detector.
C           elec.dat from gustep.f:contains information of the electrons generated
C           in the region of the detector
C   OUTPUT: photbinpe.dat: Contains info. of the photons, but now assigned to one of
C           the 384 microstrips of the detector. A histogram from this file
C           shows strp.vs.photon counts.
C           elecbinpe.dat: Contains info. of the electrons, but now assigned to one
C           of the micrsotrips. The file keeps the order in which the electrons
C           were generated by GEANT, so the graphs obtained from it could not be
C           clear/true due to possible multiple plotting of one point.
C           elecbinpe2.dat: Contains the same info. that
C           elecbinpe.dat but organized so that one point (strip) appears only
C           once with its final electron counting, so that a histogram from this
C           file is reliable and clear.
C           photbinpe2.dat: Analogous to elecbinpe2.dat. Appropriate for 
C           making the photon.vs.strip histogram.  
C     NOTE: For a detailed explanation of variables meaning, see pebin.txt
C
C***********************************************************************************

      INTEGER BIN(384), BINE(384), BINP(384)
      REAL X, Y, Z, YSTRIP(384), YV
      REAL R,UNI,GAP,SUNI
      INTEGER N, EOF, NSTRIP, I, J, K, FLAG 
      PARAMETER(UNI=0.01)
      PARAMETER(GAP=0.001)
      PARAMETER(SUNI=0.002) 
      INTEGER IPART, NOPHO, NUMED, ITRA
      INTEGER NELECT,NPAIR
      REAL GKIN(384),GK

C     Opening of files and initialization of arrays
      I=1

c     ARCHIVOS DE ENTRAD DE GEANT
      OPEN(UNIT=10, FILE='phot.dat', STATUS='UNKNOWN')
      OPEN(UNIT=12, FILE='elec.dat', STATUS='UNKNOWN')
C     ARCHIVOS DE SALIDA PARA HACER LOS PERFILES
      OPEN(UNIT=14, FILE='EBIN31432e3c185seed.dat', STATUS='UNKNOWN')
      OPEN(UNIT=15, FILE='PBIN31432e3c185seed.dat', STATUS='UNKNOWN')
      
      DO WHILE (I.LE.384) 
         BIN(I)=0
         BINE(I)=0
         BINP(I)=0
         YSTRIP(I)=1E6
         GKIN(I)=0.
         I=I+1
      END DO

C     While the file with the photons information produced by GEANT is being read,
C     the photon is assigned to the corresponding strip. photbinpe.dat is filled
C     while this process is being done.

      READ(UNIT=10,FMT=4,IOSTAT=EOF)IPART,NOPHO,X,Y
     +     ,Z,NUMED,YV
 4    FORMAT(' ',I5,3X,I10,3X,E12.6,3X,E12.6,3X
     +          ,E12.6,3X,I5,3X,E12.6)
 6    IF(EOF.EQ.0)THEN
         N=AINT((Y-GAP)/UNI )
         R=(Y-GAP-N*UNI)
         IF(Y.GE.0)THEN
            IF(R.LE.UNI-SUNI/2)THEN
               NSTRIP=N+1+192
  
               BIN(NSTRIP)=BIN(NSTRIP)+1
               IF(YSTRIP(NSTRIP).EQ.1E6)THEN
                  YSTRIP(NSTRIP)=((NSTRIP-192)*UNI)-0.006+GAP
               ENDIF
               write(*,*)'NSTRIP =',NSTRIP
             ELSE
               NSTRIP=N+2+192
               BIN(NSTRIP)=BIN(NSTRIP)+1
               IF(YSTRIP(NSTRIP).EQ.1E6)THEN
                  YSTRIP(NSTRIP)=((NSTRIP-192)*UNI)-0.006+GAP
               ENDIF
               write(*,*)'NSTRIP =',NSTRIP 
            ENDIF
         ELSE
            IF(R.LE.-(SUNI/2))THEN
               NSTRIP=N+192
   
               BIN(NSTRIP)=BIN(NSTRIP)+1
               IF(YSTRIP(NSTRIP).EQ.1E6)THEN
                  YSTRIP(NSTRIP)=((NSTRIP-192)*UNI)-0.006+GAP
               ENDIF
               write(*,*)'NSTRIP =',NSTRIP 
            ELSE
               NSTRIP=N+1+192
               BIN(NSTRIP)=BIN(NSTRIP)+1
               IF(YSTRIP(NSTRIP).EQ.1E6)THEN
                  YSTRIP(NSTRIP)=((NSTRIP-192)*UNI)-0.006+GAP
               ENDIF
               write(*,*)'NSTRIP =',NSTRIP 
            ENDIF
         ENDIF

         READ(10,5,IOSTAT=EOF)IPART,NOPHO,X,Y
     +        ,Z,NUMED,YV
 5       FORMAT(' ',I5,3X,I10,3X,E12.6,3X,E12.6,3X
     +             ,E12.6,3X,I5,3X,E12.6)  
         GO TO 6
      ENDIF  
    
      WRITE(*,*)'EOF =',EOF

C     When all the photons have been assigned to the right strip and 
C     photbinpe.dat has been written, data in the arrays YSTRIP and BIN 
C     is used to fill the new file photbinpe2.dat which contains the strip
C     number, strip Y-position and number of photons per strip. This file is
C     organized according to increasing strip number.

      I=1
      DO WHILE(I.LE.384)
         
C DEBUG         write(*,*)I,' ',YSTRIP(I),' ',BIN(I)
          WRITE(15,28)I,YSTRIP(I),BIN(I)
 28       FORMAT(1X,I5,3X,E12.6,3X,I5)
         
         I=I+1
      ENDDO   

C  **********************ELECTRON PART*****************************************
C     Reinitialization of variables commom for photons and electrons
C     or initialization of electron variables.
      EOF=0
      X=0
      Y=0
      Z=0
      N=0
      R=0
      NPAIR=0
c      FLAG=1
      
      WRITE(*,*)'Z =',Z 
      WRITE(*,*)'EOF =',EOF

C     While the file with the electrons information produced by GEANT is being read,
C     the electron is assigned to the corresponding strip. elecbinpe.dat is filled
C     while this process is being done.
     

      READ(UNIT=12,FMT=20,IOSTAT=EOF)IPART,NELECT,X,Y
     +     ,Z,GK,NUMED
 20   FORMAT(' ',I5,3X,I10,3X,E12.6,3X,E12.6,3X,E12.6,3X,E12.6,3X,I5)

C DEBUG      WRITE(*,*)X,' ',Y,' ',Z
 21   IF(EOF.EQ.0)THEN
C DEBUG         write(*,*)'NELECT =',NELECT
C DEBUG         write(*,*)'X =',X,'  Y =',Y,'  Z =',Z
C DEBUG         write(*,*)'REAL N =',(Y-GAP)/UNI
         N=AINT((Y-GAP)/UNI )
         R=(Y-GAP-N*UNI)
C DEBUG         WRITE(*,*)'N =',N
C DEBUG         WRITE(*,*)'R =',R
         IF(Y.GE.0)THEN
            IF(R.LE.UNI-SUNI/2)THEN
               NSTRIP=N+1+192
c               IF(FLAG.EQ.1)THEN
c                  J=NSTRIP
c                  FLAG=0
c               ENDIF   
               BINE(NSTRIP)=BINE(NSTRIP)+1
               NPAIR=AINT(GK/3.6E-3)
               BINP(NSTRIP)=BINP(NSTRIP)+NPAIR 
               GKIN(NSTRIP)= GKIN(NSTRIP)+GK
               IF(YSTRIP(NSTRIP).EQ.1E6)THEN
                  YSTRIP(NSTRIP)=((NSTRIP-192)*UNI)-0.006+GAP
               ENDIF
C              WRITE(13,22)NELECT,NSTRIP,YSTRIP(NSTRIP),BINE(NSTRIP),GK,
C     +                    BINP(NSTRIP)
C 22            FORMAT(1X,I10,3X,I5,3X,E12.6,3X,I5,3X,E12.6,3X,I10)
               write(*,*)'NSTRIP =',NSTRIP
            ELSE
               NSTRIP=N+2+192 
c               IF(FLAG.EQ.1)THEN
c                  J=NSTRIP
c                  FLAG=0
c               ENDIF   
               BINE(NSTRIP)=BINE(NSTRIP)+1
               NPAIR=AINT(GK/3.6E-3) 
               BINP(NSTRIP)=BINP(NSTRIP)+NPAIR 
               GKIN(NSTRIP)=GKIN(NSTRIP)+GK
               IF(YSTRIP(NSTRIP).EQ.1E6)THEN
                  YSTRIP(NSTRIP)=((NSTRIP-192)*UNI)-0.006+GAP
               ENDIF
C              WRITE(13,23)NELECT,NSTRIP,YSTRIP(NSTRIP),BINE(NSTRIP),GK,
C     +                    BINP(NSTRIP)
C 23            FORMAT(1X,I10,3X,I5,3X,E12.6,3X,I5,3X,E12.6,3X,I10) 
               write(*,*)'NSTRIP =',NSTRIP 
            ENDIF
         ELSE
            IF(R.LE.-(SUNI/2))THEN
               NSTRIP=N+192
c               IF(FLAG.EQ.1)THEN
c                  J=NSTRIP
c                  FLAG=0
c               ENDIF   
               BINE(NSTRIP)=BINE(NSTRIP)+1
               NPAIR=AINT(GK/3.6E-3) 
               BINP(NSTRIP)=BINP(NSTRIP)+NPAIR 
               GKIN(NSTRIP)=GKIN(NSTRIP)+GK
               IF(YSTRIP(NSTRIP).EQ.1E6)THEN
                  YSTRIP(NSTRIP)=((NSTRIP-192)*UNI)-0.006+GAP
               ENDIF
               write(*,*)'NSTRIP =',NSTRIP 
C              WRITE(13,24)NELECT,NSTRIP,YSTRIP(NSTRIP),BINE(NSTRIP),GK,
C     +                    BINP(NSTRIP)
C 24            FORMAT(1X,I10,3X,I5,3X,E12.6,3X,I5,3X,E12.6,3X,I10)
            ELSE
               NSTRIP=N+1+192
c               IF(FLAG.EQ.1)THEN
c                  J=NSTRIP
c                  FLAG=0
c               ENDIF   
               BINE(NSTRIP)=BINE(NSTRIP)+1
               NPAIR=AINT(GK/3.6E-3) 
               BINP(NSTRIP)=BINP(NSTRIP)+NPAIR 
               GKIN(NSTRIP)=GKIN(NSTRIP)+GK
               IF(YSTRIP(NSTRIP).EQ.1E6)THEN
                  YSTRIP(NSTRIP)=((NSTRIP-192)*UNI)-0.006+GAP
               ENDIF
C              WRITE(13,25)NELECT,NSTRIP,YSTRIP(NSTRIP),BINE(NSTRIP),GK,
C     +                    BINP(NSTRIP)
C 25            FORMAT(1X,I10,3X,I5,3X,E12.6,3X,I5,3X,E12.6,3X,I10)
               write(*,*)'NSTRIP =',NSTRIP 
            ENDIF
         ENDIF
         
         READ(12,26,IOSTAT=EOF)IPART,NELECT,X,Y
     +        ,Z,GK,NUMED
 26      FORMAT(' ',I5,3X,I10,3X,E12.6,3X,E12.6,3X,E12.6,3X,E12.6,3X,I5)

         GOTO 21
c      ELSE
c         write(*,*)'ELECTRON FILE READING COMPLETED'
      ENDIF 

      write(*,*)'END OF PHOTONS AND ELECTRONS PROCESSING' 
 
C     When all the electrons have been assigned to the right strip and 
C     elecbinpe.dat has been written, data in the arrays YSTRIP and BINE, 
C     GKIN and BINP is used to fill the new file elecbinpe2.dat which contains the
C     strip number, strip Y-position, number of electrons per strip, accumulated
C     electron kinetic energy and corresponding hypothetical number of 
C     electron-hole pairs.This file is organized according to increasing
C     strip number.

      I=1
      DO WHILE(I.LE.384)
c         IF(BINE(I).NE.0)THEN
C DEBUG         write(*,*)I,' ',YSTRIP(I),' ',BINE(I),' ',GKIN(I),' ',BINP(I)
          WRITE(14,27)I,YSTRIP(I),BINE(I),GKIN(I),BINP(I)
 27       FORMAT(1X,I5,3X,E12.6,3X,I5,3X,E12.6,3X,I10)
c         ENDIF
         I=I+1
      ENDDO   

C     Files closing

      CLOSE(10)
C      CLOSE(11)
      CLOSE(12) 
C      CLOSE(13) 
      CLOSE(14)
      CLOSE(15)
      END
 








